import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.UIManager;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jan
 */
public class Ramec extends javax.swing.JFrame {
	static ArrayList<Tym> tymy = new ArrayList<Tym>();
	static ArrayList<Hrac> hraciT1 = new ArrayList<Hrac>();
	static ArrayList<Hrac> hraciT2 = new ArrayList<Hrac>();
    /**
     * Creates new form Ramec
     */
    public Ramec() {
        initComponents();
        setTitle("Fotbalová liga");
        setSize(new Dimension(300, 300));
        setLocationRelativeTo(null);
        panel.setVisible(false);
        addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e){
				DB.closeConnection();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dialog_hrac = new DialogHrac();
        cas_minuty_panel = new javax.swing.JPanel();
        cas_minuty_label = new javax.swing.JLabel();
        cas_minuty_text = new javax.swing.JTextField();
        panel_goly = new javax.swing.JPanel();
        button_branka_v_utkani = new javax.swing.JButton();
        buton_pokutovy_kop = new javax.swing.JButton();
        button_vlastni_branka = new javax.swing.JButton();
        panel_karty = new javax.swing.JPanel();
        button_zluta = new javax.swing.JButton();
        button_cervena = new javax.swing.JButton();
        dialog_tym_vytvor = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tnazev = new javax.swing.JTextField();
        thriste = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hjmeno1 = new javax.swing.JTextField();
        hprijmeni1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        hnaro1 = new javax.swing.JTextField();
        hvaha1 = new javax.swing.JTextField();
        hpost1 = new javax.swing.JComboBox<>();
        jButton23 = new javax.swing.JButton();
        panel1 = new javax.swing.JPanel();
        panel_left1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        panel_right1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        panel_bottom1 = new javax.swing.JPanel();
        zacit_zapas = new javax.swing.JButton();
        panel_vyber = new javax.swing.JPanel();
        vyber_tym = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        panel_left = new javax.swing.JPanel();
        t1h1 = new javax.swing.JButton();
        t1h2 = new javax.swing.JButton();
        t1h3 = new javax.swing.JButton();
        t1h4 = new javax.swing.JButton();
        t1h5 = new javax.swing.JButton();
        t1h6 = new javax.swing.JButton();
        t1h7 = new javax.swing.JButton();
        t1h8 = new javax.swing.JButton();
        t1h9 = new javax.swing.JButton();
        t1h10 = new javax.swing.JButton();
        t1h11 = new javax.swing.JButton();
        panel_right = new javax.swing.JPanel();
        t2h1 = new javax.swing.JButton();
        t2h2 = new javax.swing.JButton();
        t2h3 = new javax.swing.JButton();
        t2h4 = new javax.swing.JButton();
        t2h5 = new javax.swing.JButton();
        t2h6 = new javax.swing.JButton();
        t2h7 = new javax.swing.JButton();
        t2h8 = new javax.swing.JButton();
        t2h9 = new javax.swing.JButton();
        t2h10 = new javax.swing.JButton();
        t2h11 = new javax.swing.JButton();
        panel_bottom = new javax.swing.JPanel();
        ukonceni_zapasu = new javax.swing.JButton();
        panel_skore = new javax.swing.JPanel();
        skore = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menu_stat = new javax.swing.JMenu();
        stat_hrac = new javax.swing.JMenuItem();
        stat_tym = new javax.swing.JMenuItem();
        stat_zapas = new javax.swing.JMenuItem();
        tym1label = new JLabel();
        tym2label = new JLabel();

        dialog_hrac.getContentPane().setLayout(new java.awt.GridBagLayout());

        cas_minuty_panel.setLayout(new javax.swing.BoxLayout(cas_minuty_panel, javax.swing.BoxLayout.LINE_AXIS));

        cas_minuty_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cas_minuty_label.setText("čas minuty:");
        cas_minuty_panel.add(cas_minuty_label);

        cas_minuty_text.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cas_minuty_text.setPreferredSize(new java.awt.Dimension(60, 28));
        cas_minuty_panel.add(cas_minuty_text);

        dialog_hrac.getContentPane().add(cas_minuty_panel, new java.awt.GridBagConstraints());

        panel_goly.setBorder(javax.swing.BorderFactory.createTitledBorder("gól"));
        panel_goly.setLayout(new java.awt.GridBagLayout());

        button_branka_v_utkani.setBackground(new java.awt.Color(0, 204, 51));
        button_branka_v_utkani.setText("branka v utkání");
        button_branka_v_utkani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gol(1);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panel_goly.add(button_branka_v_utkani, gridBagConstraints);

        buton_pokutovy_kop.setText("pokutový kop");
        buton_pokutovy_kop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gol(2);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panel_goly.add(buton_pokutovy_kop, gridBagConstraints);

        button_vlastni_branka.setText("vlástní branka");
        button_vlastni_branka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gol(3);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panel_goly.add(button_vlastni_branka, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        dialog_hrac.getContentPane().add(panel_goly, gridBagConstraints);

        panel_karty.setBorder(javax.swing.BorderFactory.createTitledBorder("karta"));
        panel_karty.setLayout(new java.awt.GridBagLayout());

        button_zluta.setBackground(new java.awt.Color(255, 255, 51));
        button_zluta.setText("žlutá");
        button_zluta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	karta(1);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panel_karty.add(button_zluta, gridBagConstraints);

        button_cervena.setBackground(new java.awt.Color(255, 0, 0));
        button_cervena.setText("červená");
        button_cervena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	karta(2);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_karty.add(button_cervena, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        dialog_hrac.getContentPane().add(panel_karty, gridBagConstraints);

        dialog_tym_vytvor.getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("tým"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Název týmu");
        jPanel1.add(jLabel2, new java.awt.GridBagConstraints());

        jLabel1.setText("Domovské hřiště");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel1, gridBagConstraints);

        tnazev.setText("jTextField1");
        tnazev.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel1.add(tnazev, gridBagConstraints);

        thriste.setText("jTextField2");
        thriste.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(thriste, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        dialog_tym_vytvor.getContentPane().add(jPanel1, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("hráči"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Jméno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Příjmení");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel4, gridBagConstraints);

        hjmeno1.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel3.add(hjmeno1, gridBagConstraints);

        hprijmeni1.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel3.add(hprijmeni1, gridBagConstraints);

        jLabel5.setText("D.narození");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Váha");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Post");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel7, gridBagConstraints);

        jLabel8.setText("1.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel3.add(jLabel8, gridBagConstraints);

        hnaro1.setText("jTextField5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel3.add(hnaro1, gridBagConstraints);

        hvaha1.setText("jTextField6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        jPanel3.add(hvaha1, gridBagConstraints);

        hpost1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brankář", "Obránce", "Záložník", "Útočník" }));
        hpost1.setSelectedIndex(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        jPanel3.add(hpost1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        dialog_tym_vytvor.getContentPane().add(jPanel3, gridBagConstraints);

        jButton23.setBackground(new java.awt.Color(0, 255, 51));
        jButton23.setText("Založit tým");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        dialog_tym_vytvor.getContentPane().add(jButton23, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        panel1.setLayout(new java.awt.GridBagLayout());

        panel_left1.setLayout(new java.awt.GridBagLayout());

        String[] strings = new String[tymy.size()];
        for (int i = 0; i < strings.length; i++) {
			strings[i] = tymy.get(i).nazev;
		}
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        panel_left1.add(jScrollPane1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panel1.add(panel_left1, gridBagConstraints);

        panel_right1.setLayout(new java.awt.GridBagLayout());

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        panel_right1.add(jScrollPane2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panel1.add(panel_right1, gridBagConstraints);

        panel_bottom1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        panel_bottom1.setLayout(new java.awt.GridBagLayout());

        zacit_zapas.setText("Začít zápas");
        zacit_zapas.setBackground(new java.awt.Color(0, 204, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        panel_bottom1.add(zacit_zapas, gridBagConstraints);
        zacit_zapas.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				zacit_zapas();
			}
		});

        JButton vycistiDB = new JButton("Vyčisti DB");
        vycistiDB.setBackground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        panel_bottom1.add(vycistiDB, gridBagConstraints);
        vycistiDB.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				DB.vycistiDB();
			}
		});

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panel1.add(panel_bottom1, gridBagConstraints);

        hlasky = new JLabel("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.anchor = GridBagConstraints.CENTER;
        panel1.add(hlasky, gridBagConstraints);

        vyber_tym.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        vyber_tym.setText("vyber týmy");

        javax.swing.GroupLayout panel_vyberLayout = new javax.swing.GroupLayout(panel_vyber);
        panel_vyber.setLayout(panel_vyberLayout);
        panel_vyberLayout.setHorizontalGroup(
            panel_vyberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
            .addGroup(panel_vyberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_vyberLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(vyber_tym)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_vyberLayout.setVerticalGroup(
            panel_vyberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
            .addGroup(panel_vyberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_vyberLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(vyber_tym)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        panel1.add(panel_vyber, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(panel1, gridBagConstraints);

        panel.setLayout(new java.awt.GridBagLayout());

        panel_left.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panel_left.add(tym1label, gridBagConstraints);
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panel_left.add(t1h1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_left.add(t1h2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_left.add(t1h3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_left.add(t1h4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_left.add(t1h5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_left.add(t1h6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_left.add(t1h7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_left.add(t1h8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_left.add(t1h9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_left.add(t1h10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_left.add(t1h11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panel.add(panel_left, gridBagConstraints);

        panel_right.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panel_right.add(tym2label, gridBagConstraints);
        
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panel_right.add(t2h1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_right.add(t2h2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_right.add(t2h3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_right.add(t2h4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_right.add(t2h5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_right.add(t2h6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_right.add(t2h7, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_right.add(t2h8, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_right.add(t2h9, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_right.add(t2h10, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panel_right.add(t2h11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panel.add(panel_right, gridBagConstraints);

        panel_bottom.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        panel_bottom.setLayout(new java.awt.GridBagLayout());

        ukonceni_zapasu.setText("Ukončit zápas");
        ukonceni_zapasu.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				ukoncitZapas();
			}
		});
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panel_bottom.add(ukonceni_zapasu, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panel.add(panel_bottom, gridBagConstraints);

        skore.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        skore.setText("0:0");

        javax.swing.GroupLayout panel_skoreLayout = new javax.swing.GroupLayout(panel_skore);
        panel_skore.setLayout(panel_skoreLayout);
        panel_skoreLayout.setHorizontalGroup(
            panel_skoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 89, Short.MAX_VALUE)
            .addGroup(panel_skoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_skoreLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(skore)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel_skoreLayout.setVerticalGroup(
            panel_skoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
            .addGroup(panel_skoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_skoreLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(skore)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        panel.add(panel_skore, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(panel, gridBagConstraints);

        JMenu menu_edit = new JMenu("Editace");
        JMenuItem vyt_tym = new JMenuItem("Nový tým");
        menu_edit.add(vyt_tym);
        JMenuItem vyt_hrace = new JMenuItem("Nový hráč");
        menu_edit.add(vyt_hrace);
        menuBar.add(menu_edit);
        vyt_tym.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				new NovyTym();
			}
		});
        vyt_hrace.addActionListener(new ActionListener() {
 			@Override
 			public void actionPerformed(ActionEvent e) {
 				new NovyHrac();
 			}
 		});
         
        menu_stat.setText("Žebříčky");
        stat_hrac.setText("Hráči");
        menu_stat.add(stat_hrac);
        stat_tym.setText("Týmy");
        menu_stat.add(stat_tym);
        stat_zapas.setText("Zápasy");
        menu_stat.add(stat_zapas);
        menuBar.add(menu_stat);
        stat_hrac.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				new StatHrac();
			}
		});
        stat_tym.addActionListener(new ActionListener() {
 			@Override
 			public void actionPerformed(ActionEvent e) {
 				new StatTym();
 			}
 		});
        stat_zapas.addActionListener(new ActionListener() {
 			@Override
 			public void actionPerformed(ActionEvent e) {
 				new StatZapas();
 			}
 		});
         
        setJMenuBar(menuBar);

        dialog_hrac.setSize(160, 260);
        
        pack();
        dialog_hrac.setLocationRelativeTo(null);
    }                        

    protected void ukoncitZapas() {
    	DB.aktualizace_poradi();
		DB.closeConnection();
		dispose();
		start();
	}

	protected void gol(int typGolu) {
    	if (cas_minuty_text.getText().length() > 0) {
        	dialog_hrac.setVisible(false);
        	switch (typGolu) {
    		case 1:
    			DB.gol("BRANKA_V_UTKANI", ((DialogHrac)dialog_hrac).hrac, cas_minuty_text.getText());
    			break;
    		case 2:
    			DB.gol("POKUTOVY_KOP", ((DialogHrac)dialog_hrac).hrac, cas_minuty_text.getText());
    			break;
    		case 3:
    			DB.gol("VLASTNI_BRANKA", ((DialogHrac)dialog_hrac).hrac, cas_minuty_text.getText());
    			break;
    		default:
    			break;
    		}
        	DB.updateSkore(skore);
		}
	}

	protected void karta(int i) {
    	dialog_hrac.setVisible(false);
		if (i == 2) {
			((DialogHrac)dialog_hrac).hrac.karta = 2;
		} else if (((DialogHrac)dialog_hrac).hrac.karta == 1) {
			((DialogHrac)dialog_hrac).hrac.karta = 2;
		} else ((DialogHrac)dialog_hrac).hrac.karta = 1;
		updateColors();
	}

	private void updateColors() {
		updateColor(t1h1, hraciT1.get(1-1).karta);
		updateColor(t1h2, hraciT1.get(2-1).karta);
		updateColor(t1h3, hraciT1.get(3-1).karta);
		updateColor(t1h4, hraciT1.get(4-1).karta);
		updateColor(t1h5, hraciT1.get(5-1).karta);
		updateColor(t1h6, hraciT1.get(6-1).karta);
		updateColor(t1h7, hraciT1.get(7-1).karta);
		updateColor(t1h8, hraciT1.get(8-1).karta);
		updateColor(t1h9, hraciT1.get(9-1).karta);
		updateColor(t1h10, hraciT1.get(10-1).karta);
		updateColor(t1h11, hraciT1.get(11-1).karta);
		updateColor(t2h1, hraciT2.get(1-1).karta);
		updateColor(t2h2, hraciT2.get(2-1).karta);
		updateColor(t2h3, hraciT2.get(3-1).karta);
		updateColor(t2h4, hraciT2.get(4-1).karta);
		updateColor(t2h5, hraciT2.get(5-1).karta);
		updateColor(t2h6, hraciT2.get(6-1).karta);
		updateColor(t2h7, hraciT2.get(7-1).karta);
		updateColor(t2h8, hraciT2.get(8-1).karta);
		updateColor(t2h9, hraciT2.get(9-1).karta);
		updateColor(t2h10, hraciT2.get(10-1).karta);
		updateColor(t2h11, hraciT2.get(11-1).karta);
	}

	private void updateColor(JButton hracb, int karta) {
		switch (karta) {
		case 0:
			break;
		case 1:
			hracb.setBackground(Color.yellow);
			hracb.setForeground(Color.yellow);
			break;
		case 2:
			hracb.setBackground(Color.red);
			hracb.setForeground(Color.red);
			break;
		default:
			break;
		}
	}

	private void zacit_zapas() {
		int t1id = tymy.get(jList1.getSelectedIndex()).id;
		int t2id = tymy.get(jList2.getSelectedIndex()).id;
		boolean ok = DB.novyZapas(t1id, t2id);
		if (t1id != 0 && t2id != 0 && t1id != t2id && ok) {
			hraciT1 = DB.nactiHrace(t1id);
			hraciT2 = DB.nactiHrace(t2id);
			popiskyHracu();
			popiskyTymu();
			panel1.setVisible(false);
			panel.setVisible(true);
	        setSize(new Dimension(500, 400));
	        setLocationRelativeTo(null);
			repaint();
		} else if (!ok) {
			vyber_tym.setText("Tyto týmy spolu zde již hrály!");
		} else vyber_tym.setText("Tým nemůže hrát sám :(");
	}
    
    private void popiskyTymu() {
		tym1label.setText(tymy.get(jList1.getSelectedIndex()).nazev);
		tym2label.setText(tymy.get(jList2.getSelectedIndex()).nazev);
	}

	private void popiskyHracu() {
    	popisekHrace(t1h1,1,1);
    	popisekHrace(t1h2,1,2);
    	popisekHrace(t1h3,1,3);
    	popisekHrace(t1h4,1,4);
    	popisekHrace(t1h5,1,5);
    	popisekHrace(t1h6,1,6);
    	popisekHrace(t1h7,1,7);
    	popisekHrace(t1h8,1,8);
    	popisekHrace(t1h9,1,9);
    	popisekHrace(t1h10,1,10);
    	popisekHrace(t1h11,1,11);
    	popisekHrace(t2h1,2,1);
    	popisekHrace(t2h2,2,2);
    	popisekHrace(t2h3,2,3);
    	popisekHrace(t2h4,2,4);
    	popisekHrace(t2h5,2,5);
    	popisekHrace(t2h6,2,6);
    	popisekHrace(t2h7,2,7);
    	popisekHrace(t2h8,2,8);
    	popisekHrace(t2h9,2,9);
    	popisekHrace(t2h10,2,10);
    	popisekHrace(t2h11,2,11);
	}

	private void popisekHrace(JButton hracButt, int tym, int i) {
		hracButt.setText(
				tym == 1 ? 
				hraciT1.get(i-1).jmeno+" "+hraciT1.get(i-1).prijmeni :
				hraciT2.get(i-1).jmeno+" "+hraciT2.get(i-1).prijmeni);
		hracButt.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				akceHrac(i-1);
			}
			private void akceHrac(int i) {
				((DialogHrac) dialog_hrac).aktivuj(tym == 1 ? hraciT1.get(i) : hraciT2.get(i));
			}
		});
	}
	
	/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    	start();
    }
    
    public static void start() {
       	//DB.connect();
    	//tymy = DB.nactiTymy();
        try {
        	UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ramec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ramec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ramec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ramec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ramec().setVisible(true);
            }
        });
    }

    private JLabel hlasky;
    private javax.swing.JButton buton_pokutovy_kop;
    private javax.swing.JButton button_branka_v_utkani;
    private javax.swing.JButton button_cervena;
    private javax.swing.JButton button_vlastni_branka;
    private javax.swing.JButton button_zluta;
    private javax.swing.JLabel cas_minuty_label;
    private javax.swing.JPanel cas_minuty_panel;
    private javax.swing.JTextField cas_minuty_text;
    private javax.swing.JDialog dialog_hrac;
    private javax.swing.JDialog dialog_tym_vytvor;
    private javax.swing.JTextField hjmeno1;
    private javax.swing.JTextField hnaro1;
    private javax.swing.JComboBox<String> hpost1;
    private javax.swing.JTextField hprijmeni1;
    private javax.swing.JTextField hvaha1;
    private javax.swing.JButton t2h1;
    private javax.swing.JButton t2h10;
    private javax.swing.JButton t2h11;
    private javax.swing.JButton t1h1;
    private javax.swing.JButton t1h2;
    private javax.swing.JButton t1h3;
    private javax.swing.JButton t1h4;
    private javax.swing.JButton t1h5;
    private javax.swing.JButton t1h6;
    private javax.swing.JButton t1h7;
    private javax.swing.JButton t1h8;
    private javax.swing.JButton t2h2;
    private javax.swing.JButton t1h9;
    private javax.swing.JButton t1h10;
    private javax.swing.JButton t1h11;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton t2h3;
    private javax.swing.JButton t2h4;
    private javax.swing.JButton t2h5;
    private javax.swing.JButton t2h6;
    private javax.swing.JButton t2h7;
    private javax.swing.JButton t2h8;
    private javax.swing.JButton t2h9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel tym1label;
    private javax.swing.JLabel tym2label;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menu_stat;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel_bottom;
    private javax.swing.JPanel panel_bottom1;
    private javax.swing.JPanel panel_goly;
    private javax.swing.JPanel panel_karty;
    private javax.swing.JPanel panel_left;
    private javax.swing.JPanel panel_left1;
    private javax.swing.JPanel panel_right;
    private javax.swing.JPanel panel_right1;
    private javax.swing.JPanel panel_skore;
    private javax.swing.JPanel panel_vyber;
    private javax.swing.JLabel skore;
    private javax.swing.JMenuItem stat_hrac;
    private javax.swing.JMenuItem stat_tym;
    private javax.swing.JMenuItem stat_zapas;
    private javax.swing.JTextField thriste;
    private javax.swing.JTextField tnazev;
    private javax.swing.JButton ukonceni_zapasu;
    private javax.swing.JLabel vyber_tym;
    private javax.swing.JButton zacit_zapas;
    // End of variables declaration                   
}
